### ISSUE TITLE
[milestone] v1

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/configure-bun-action#2]
- [x] make sure it works
- [x] make sure readme is good
- [x] publish to gh marketplace
- [ ] have actions4git/add-commit-push be ready
- [x] https://github.com/jcbhmr/hello-world-bun-action
